### PR TITLE
change some "data" fields to postgres TEXT

### PR DESCRIPTION
**Pull request by haraldschilly**
when I tried to connect to moodle, sequelize threw some errors about too short fields (data in accesstoken).

this here replaces string by text, which fixes this.

I'm also aware that my other PR didn't build it, and well, this one is in conflict. I can clean this up as one PR... 

(I don't know what the `#...` signs in the source code mean or do, but it built fine and runs)

### CODE REVIEW

**Comment by MahmoudAbdo90** [comment]
@haraldschilly  Do you have a code sample ? I am trying to get it working but by creating new entries in some of the tables that I have already

**Comment by Cvmcosta** [comment]
Merged to master

**Comment by Cvmcosta** [comment]
Ill be updating the package soon.

**Comment by haraldschilly** [comment]
thank you!

**Comment by haraldschilly** [comment]
> @haraldschilly Do you have a code sample ? 

no, but the issue was easy to spot ... some authentication tokens (or whatever) were too long for the fields. ... and using "TEXT" in the context of postgresql is mostly fine anyways.

**Comment by Cvmcosta** [comment]
Package updated :) Thanks a lot

**Pull request merged**
